### ISSUE TITLE
作業メモ for using mongo 2.1

### ISSUE THREAD

**Issue by okkez** [okkez/fluent-plugin-mongo#1]
mongo 2.1 を使うようにするための作業のメモ。

2.0より前。

``` ruby
db = Mongo::MongoClient.new(@host, @port, @connection_options).db(@database)
authenticate(db)
```

2.0以降。

``` ruby
client = Mongo::Client.new([server1, server2], options)
```

クライアントの初期化方法が違う。

**Comment by okkez** [comment]
例外クラスの名前も全然違う。

**Comment by okkez** [comment]
小手先のコード書き換えでバージョンアップするのは無理そう。

**Comment by okkez** [comment]
元のコードはmongodbの用語とかクラス名と合ってない箇所があって少しわかりづらいな。

**Comment by okkez** [comment]
cursorのAPIが全然違うような。。。

**Comment by okkez** [comment]
新しい方のcursorは `to_enum` したのを使えるので `next` で回すこともできる。

**Comment by okkez** [comment]
in_mongo_tail はテストが通るところまでできた。

**Comment by okkez** [comment]
`collection.insert_many` したときのエラー処理がちょっとややこしいかも。

**Comment by okkez** [comment]
いや、ややこしいというか `collection.insert_many` って失敗するのか？
失敗したレコードを取り出せるのか？

**Comment by cosmo0920** [comment]
`collection.insert_many` は `Result` を返すとドキュメントに書いているのに正常の時しか返していないように見えました。何故かエラーが起きた時は返り値が空です。

**Comment by cosmo0920** [comment]
不正なレコードを含まないようにして `collection.insert_many` する場合は少しだけ書き換えてテストが通るようになりました。 https://github.com/cosmo0920/fluent-plugin-mongo/tree/use-mongo-2-output

**Comment by okkez** [comment]
テストを通すのが目的じゃなくて、不正なレコードを含むときのRecover featureが実現可能かどうか調べて欲しいです。

**Comment by cosmo0920** [comment]
`collection.insert_many` で返すとされている `Result` には `invalid_records` のようなフィールドは無いです。 https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/bulk_write/result.rb#L67 
Recover featureを実現するにはdriverをいじらないといけないです。

**Comment by okkez** [comment]
例えば、insertで一件ずつ登録するのとinsert_manyで一気に登録するので性能に差が無ければinsertで一件ずつ登録するのもアリかなぁと思います。

**Comment by cosmo0920** [comment]
一件づつだとinsert_oneでinsertに失敗した場合は `Mongo::Error::OperationFailure` が返ってくるのでこれを利用すればできます。 https://github.com/cosmo0920/fluent-plugin-mongo/commit/3cb818d14ae0690c6e3d4db2e5967c2f0294fb23

**Comment by okkez** [comment]
もう一つ別案ですが、`insert_many`の内部で使っている`BulkWrite`というのを直接使うのはどうでしょうか？
あまり調べてませんが、insert_manyが内部で使っているクラスなので何か取れるかもしれません。

**Comment by cosmo0920** [comment]
調べたところ、`insert_many`の内部で確かに `BulkWrite` が使われていますが、`collection.insert_many` の内部で `insert_one` を付与 https://github.com/mongodb/mongo-ruby-driver/blob/87a8c09509c0ecdbe2adbd96a809c7720baaed8e/lib/mongo/collection.rb#L346 して `BulkWrite#execute` では `insert_one` の operation typeの付いたrequestsをoperationsへ変換 https://github.com/mongodb/mongo-ruby-driver/blob/87a8c09509c0ecdbe2adbd96a809c7720baaed8e/lib/mongo/bulk_write.rb#L150 し、eachしている https://github.com/mongodb/mongo-ruby-driver/blob/87a8c09509c0ecdbe2adbd96a809c7720baaed8e/lib/mongo/bulk_write.rb#L53 だけでした。なので、bulk-insertとは言いつつも内部でinsert_oneへ翻訳されeachされるか、露わにeachするかの違いしか無さそうに見えます。

**Comment by okkez** [comment]
コードを見た感じではそうですね。
`insert_one`と`insert_many`に性能差があるかどうかベンチマークを取ってください。
mongo gem の 1.9 と比較もしたいのでそちらも確認して報告してください。

mongo gem のバージョンを上げても性能が劣化しないことと、`insert_one`と`insert_many`で性能に差が無いことを確認したいです。もし、性能が著しく劣化するなら mongo gem の方を直さないといけないかもしれません。

**Comment by cosmo0920** [comment]
insert_manyだけで出来ないかissueを立ててみました。https://jira.mongodb.org/browse/RUBY-1062 
~~リプライを見る限り出来そうな方法があるようです。~~
勘違いでした。成功したレコードは取って来れますが、そうでない場合は無理そうです。。

**Comment by cosmo0920** [comment]
ベンチマークを取ってみました。

## 1.x系最新(1.12.3)

``` log
insert one by one (legacy)
       user     system      total        real
   2.880000   0.530000   3.410000 (  5.365804)
bulk insert (legacy)
       user     system      total        real
   0.200000   0.010000   0.210000 (  0.314387)
```

## 2.x系最新(2.1.2)

``` log
insert one by one
       user     system      total        real
   4.670000   0.860000   5.530000 (  8.229355)
bulk insert
       user     system      total        real
   0.150000   0.000000   0.150000 (  0.238776)
```

でした。
~~ベンチマークに使ったコードをどこかに上げておいた方がよいでしょうか。~~
ベンチマークに用いたコードはこちら https://github.com/okkez/fluent-plugin-mongo/issues/1#issuecomment-151371060

**Comment by cosmo0920** [comment]
バグトラッカーで教えてもらったやり方は以下:

> This is an example of an unordered insert using the Ruby driver:
> 
> ``` ruby
> r = begin; client[:test].insert_many([{ _id: 1 }, { _id: 1 }, { _id: 2 }], :ordered => false); rescue => ex; ex;end
> r.result
> => {"n_inserted"=>2,
>  "n"=>2,
>  "inserted_ids"=>[1, 1, 2],
>  "writeErrors"=>[{"index"=>1, "code"=>11000, "errmsg"=>"E11000 duplicate key error index: admin.test.$_id_ dup key: { : 1 }"}]}
> client[:test].find.to_a
> => [{"_id"=>1}, {"_id"=>2}]
> ```
> 
> and then an ordered insert
> 
> ``` ruby
> r = begin; client[:test].insert_many([{ _id: 1 }, { _id: 1 }, { _id: 2 }], :ordered => true); rescue => ex; ex;end
> r.result
> => {"n_inserted"=>1,
>  "n"=>1,
>  "inserted_ids"=>[1, 1, 2],
>  "writeErrors"=>[{"index"=>1, "code"=>11000, "errmsg"=>"E11000 duplicate key error index: admin.test.$_id_ dup key: { : 1 }"}]}
> client[:test].find.to_a
> => [{"_id"=>1}]
> ```

**Comment by cosmo0920** [comment]
## Mongo Driver 1系最新向けベンチマークコード

https://gist.github.com/cosmo0920/b33c96e071c5c6923304#file-mongo_insert_bench_legacy-rb

## Mongo Driver 2系最新向けのベンチマークコード

https://gist.github.com/cosmo0920/b33c96e071c5c6923304#file-mongo_insert_bench_latest-rb

**Comment by okkez** [comment]
サンプルコードが実際のユースケースに合っていない。fluent-plugin-mongoでは`_id`を指定してinsertすることはない。
`_id`を使わないケースでduplicate key以外のエラーを起こすケースを検証した方がよい。

**Comment by cosmo0920** [comment]
https://jira.mongodb.org/browse/RUBY-1062?focusedCommentId=1075823&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1075823

> You can see which records were invalid in the information at the 'writeErrors' key of the operation result. For example, in my previous comment, you can see that the second document attempted to be inserted had a duplicate key error; the 'writeErrors' indicates that the document at index 1 of the attempted inserts had a E11000 duplicate key error.
> 
> You can get the same functionality of the 1.x series driver using the operation result writeErrors.

見た感じ `writeErrors` の中にエラー情報が詰め込まれ、 `writeErrors` の情報を見れば 1.x系と同じ機能はありますよ〜。と言っているように見えます。が、1.x系ではそのまま取れていたエラーの起きたレコードは2.x系ではそのままは取れなそうなので、2.x系でどうするかは考える必要がありますね。。

**Comment by cosmo0920** [comment]
他にも色々とやり取りしていたら、MongoDBの仕様書について色々と指摘を頂いた。

https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#results
によると、ResultにinsertedIdsが入ってくるものの、idは使っていないのでbulk insertは諦める方向で行くのが良いか。

> We must follow this specification for how the driver sends insert operations and what structure the result object has so we won't change it.

ref: https://jira.mongodb.org/browse/RUBY-1062?focusedCommentId=1085959&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1085959

bulk insertのResult型は仕様で定まっているのでruby driver側でごにょごにょ出来る問題でもない様子。

**Comment by cosmo0920** [comment]
> We include the write error from the server in the result object and only the index is included for efficiency.

ref: https://jira.mongodb.org/browse/RUBY-1062?focusedCommentId=1085959&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1085959

なぜindexのみだけ返すようにしているかと言うと、効率のためらしい。

**Comment by okkez** [comment]
わかりましたー。ありがとうございます。
1. 遅くなるのを受け入れて1レコードずつ処理する
2. bulk insert してエラー時に失敗したのを放置する
3. bulk insert してエラーになったやつを fluent-plugin-mongo 側できちんと検出する

のどれかですかね。

**Comment by okkez** [comment]
@cosmo0920 ここまでの内容をまとめて fluent/fluent-plugin-mongo に英語でissueを立ててもらえませんか？

**Comment by cosmo0920** [comment]
fluent/fluent-plugin-mongoへIssueを立てました。不足している事があったら適宜補足なりツッコミをお願いします。

**Comment by okkez** [comment]
そう言えば、ベンチマークスクリプトはこんな感じで書けるよ、というのを伝えるのを忘れてました。
ベンチマーク結果にラベルが付けられます。

``` ruby
require 'mongo'
require 'benchmark'

# setup
Mongo::Logger.level = Logger::WARN
options = {}
options[:database] = 'latest_bench'
client = Mongo::Client.new(["localhost:27017"], options)

records = []
10000.times do |i|
  records << { "#{i}" => i }
end

# insert one by one
Benchmark.bm do |x|
  x.report("insert one 1") { 10000.times { |i| client['test_collection'].insert_one("i#{i}" => i) } }
  x.report("insert one 2") { records.each{|r| client['test_collection'].insert_one(r) } }
  x.report("bulk insert") { client['test_collection'].insert_many(records) }
end

# teardown
client['test_collection'].drop
```

**Comment by cosmo0920** [comment]
うお、このissueをすっかり放置してました。
https://github.com/fluent/fluent-plugin-mongo/issues/65 が閉じられて、mongoクライアントもバージョンアップできたので閉じておいてもらえますか？
